openapi: 3.0.0
info:
  title: "API"
  version: "1.0.0"
paths:
  /valid/response/header:
    get:
      description: no `response.header` required
      x-controller:
        - valid.response.header
      responses: 
        200:
          description: ok
        default:
          description: default
    post:
      description: "`response.header` optional, valid"
      x-controller:
        - valid.response.header
      responses:
        200:
          description: ok
          headers:
            x-reponse-header:
              required: false
              schema:
                type: string
                maxLength: 5
        default:
          description: default
    patch:
      description: "`response.header` optional, invalid"
      x-controller:
        - valid.response.header
      responses:
        200:
          description: ok
          headers:
            x-reponse-header:
              required: false
              schema:
                type: string
                maxLength: 5
            
        default:
          description: default
    delete:
      description: "`response.header` required, valid"
      x-controller:
        - valid.response.header
      responses:
        200:
          description: ok
          headers:
            x-reponse-header:
              required: true
              schema:
                type: string
                maxLength: 5
            
        default:
          description: default
    put:
      description: "`response.header` required, invalid"
      x-controller:
        - valid.response.header
      responses:
        200:
          description: ok
          headers:
            x-reponse-header:
              required: true
              schema:
                type: string
                maxLength: 5
            
        default:
          description: default
